"""add hot-path indexes on instagram_posts, videos.status, images.batch_id, articles.translation_group_id

Revision ID: 0359b4bf9dff
Revises: u5v6w7x8y9z0
Create Date: 2026-07-05 22:10:25.904990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0359b4bf9dff'
down_revision: Union[str, Sequence[str], None] = 'u5v6w7x8y9z0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_images_batch_id'), 'images', ['batch_id'], unique=False)
    op.create_index('ix_instagram_posts_status_scheduled_at', 'instagram_posts', ['status', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_videos_status'), 'videos', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_status'), table_name='videos')
    op.drop_index('ix_instagram_posts_status_scheduled_at', table_name='instagram_posts')
    op.drop_index(op.f('ix_images_batch_id'), table_name='images')
    # ### end Alembic commands ###
