"""extract instagram post companions into post_companions table

Revision ID: f0a7f5dc6258
Revises: eb5b48ad13f2
Create Date: 2026-07-06

Code review A2: instagram_posts carried feed/reel/story/outpost state in
one table (5 parallel status-ish columns, 3 creation-id-ish columns, 2 delay
columns, 2 scheduled-at columns). This extracts the story/reel companion
state into a child table — one row per companion kind, so a future
companion type is a new row shape, not new parent-table columns.

Hand-written (not autogenerated) because this moves data, not just schema.
Every existing story_*/reel_*/outpost_reel_status value is preserved
verbatim in the new table before the old columns are dropped.
"""
import uuid
from datetime import datetime, timezone

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ARRAY, UUID

revision = 'f0a7f5dc6258'
down_revision = 'eb5b48ad13f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        'post_companions',
        sa.Column('id', UUID(as_uuid=True), primary_key=True),
        sa.Column('post_id', UUID(as_uuid=True), sa.ForeignKey('instagram_posts.id', ondelete='CASCADE'), nullable=False),
        sa.Column('kind', sa.String(16), nullable=False),
        sa.Column('delay_minutes', sa.Integer, nullable=True),
        sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.String(32), nullable=True),
        sa.Column('outpost_status', sa.String(32), nullable=True),
        sa.Column('creation_id', sa.String(128), nullable=True),
        sa.Column('media_id', sa.String(128), nullable=True),
        sa.Column('video_id', UUID(as_uuid=True), nullable=True),
        sa.Column('video_filename', sa.String(512), nullable=True),
        sa.Column('media_ids', ARRAY(sa.String(128)), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    )
    op.create_unique_constraint('uq_post_companions_post_kind', 'post_companions', ['post_id', 'kind'])
    op.create_index('ix_post_companions_post_id', 'post_companions', ['post_id'])
    op.create_check_constraint('ck_post_companions_kind', 'post_companions', "kind IN ('story', 'reel')")
    op.create_check_constraint(
        'ck_post_companions_status', 'post_companions',
        "status IS NULL OR status IN ('pending', 'processing', 'posted', 'failed', 'remote_scheduled')",
    )

    pc_table = sa.table(
        'post_companions',
        sa.column('id', UUID(as_uuid=True)),
        sa.column('post_id', UUID(as_uuid=True)),
        sa.column('kind', sa.String),
        sa.column('delay_minutes', sa.Integer),
        sa.column('scheduled_at', sa.DateTime(timezone=True)),
        sa.column('status', sa.String),
        sa.column('outpost_status', sa.String),
        sa.column('creation_id', sa.String),
        sa.column('media_id', sa.String),
        sa.column('video_id', UUID(as_uuid=True)),
        sa.column('video_filename', sa.String),
        sa.column('media_ids', ARRAY(sa.String)),
        sa.column('created_at', sa.DateTime(timezone=True)),
        sa.column('updated_at', sa.DateTime(timezone=True)),
    )

    conn = op.get_bind()
    rows = conn.execute(sa.text("""
        SELECT id, story_delay_minutes, story_scheduled_at, story_status, story_media_ids,
               reel_delay_minutes, reel_scheduled_at, reel_status, outpost_reel_status,
               reel_creation_id, reel_media_id, reel_video_id, reel_video_filename
        FROM instagram_posts
    """)).mappings().all()

    story_rows = []
    reel_rows = []
    now = datetime.now(timezone.utc)
    for row in rows:
        if any(row[k] is not None for k in (
            'story_delay_minutes', 'story_scheduled_at', 'story_status', 'story_media_ids',
        )):
            story_rows.append({
                'id': uuid.uuid4(), 'post_id': row['id'], 'kind': 'story',
                'delay_minutes': row['story_delay_minutes'], 'scheduled_at': row['story_scheduled_at'],
                'status': row['story_status'], 'outpost_status': None,
                'creation_id': None, 'media_id': None, 'video_id': None, 'video_filename': None,
                'media_ids': row['story_media_ids'],
                'created_at': now, 'updated_at': now,
            })
        if any(row[k] is not None for k in (
            'reel_delay_minutes', 'reel_scheduled_at', 'reel_status', 'outpost_reel_status',
            'reel_creation_id', 'reel_media_id', 'reel_video_id', 'reel_video_filename',
        )):
            reel_rows.append({
                'id': uuid.uuid4(), 'post_id': row['id'], 'kind': 'reel',
                'delay_minutes': row['reel_delay_minutes'], 'scheduled_at': row['reel_scheduled_at'],
                'status': row['reel_status'], 'outpost_status': row['outpost_reel_status'],
                'creation_id': row['reel_creation_id'], 'media_id': row['reel_media_id'],
                'video_id': row['reel_video_id'], 'video_filename': row['reel_video_filename'],
                'media_ids': None,
                'created_at': now, 'updated_at': now,
            })

    if story_rows:
        conn.execute(pc_table.insert(), story_rows)
    if reel_rows:
        conn.execute(pc_table.insert(), reel_rows)

    op.drop_constraint('ck_instagram_posts_reel_status', 'instagram_posts', type_='check')
    for col in (
        'story_delay_minutes', 'story_scheduled_at', 'story_status', 'story_media_ids',
        'reel_delay_minutes', 'reel_scheduled_at', 'reel_status', 'reel_media_id',
        'reel_creation_id', 'reel_video_filename', 'reel_video_id', 'outpost_reel_status',
    ):
        op.drop_column('instagram_posts', col)


def downgrade() -> None:
    op.add_column('instagram_posts', sa.Column('story_delay_minutes', sa.Integer, nullable=True))
    op.add_column('instagram_posts', sa.Column('story_scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('instagram_posts', sa.Column('story_status', sa.String(32), nullable=True))
    op.add_column('instagram_posts', sa.Column('story_media_ids', ARRAY(sa.String(128)), nullable=True))
    op.add_column('instagram_posts', sa.Column('reel_delay_minutes', sa.Integer, nullable=True))
    op.add_column('instagram_posts', sa.Column('reel_scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('instagram_posts', sa.Column('reel_status', sa.String(32), nullable=True))
    op.add_column('instagram_posts', sa.Column('reel_media_id', sa.String(128), nullable=True))
    op.add_column('instagram_posts', sa.Column('reel_creation_id', sa.String(128), nullable=True))
    op.add_column('instagram_posts', sa.Column('reel_video_filename', sa.String(512), nullable=True))
    op.add_column('instagram_posts', sa.Column('reel_video_id', UUID(as_uuid=True), nullable=True))
    op.add_column('instagram_posts', sa.Column('outpost_reel_status', sa.String(32), nullable=True))
    op.create_check_constraint(
        'ck_instagram_posts_reel_status', 'instagram_posts',
        "reel_status IS NULL OR reel_status IN ('pending', 'processing', 'posted', 'failed', 'remote_scheduled')",
    )

    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE instagram_posts p SET
            story_delay_minutes = c.delay_minutes,
            story_scheduled_at  = c.scheduled_at,
            story_status        = c.status,
            story_media_ids     = c.media_ids
        FROM post_companions c
        WHERE c.post_id = p.id AND c.kind = 'story'
    """))
    conn.execute(sa.text("""
        UPDATE instagram_posts p SET
            reel_delay_minutes   = c.delay_minutes,
            reel_scheduled_at    = c.scheduled_at,
            reel_status          = c.status,
            outpost_reel_status  = c.outpost_status,
            reel_creation_id     = c.creation_id,
            reel_media_id        = c.media_id,
            reel_video_id        = c.video_id,
            reel_video_filename  = c.video_filename
        FROM post_companions c
        WHERE c.post_id = p.id AND c.kind = 'reel'
    """))

    op.drop_table('post_companions')
